name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ls -la 
    - name: List files in the repository
      run: sudo  apt-get install openjdk-11-jdk
    - name: List files in the repository
      run: ./gradlew getRuntime
    - name: build artifacts
      run: cd docker/simple
    - name: image build
      run: ./docker-build.sh
    - name: image find
      run: docker images -a
