name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: list of files
      run: ls -la
    - name: clone repository
      run: git clone https://github.com/moqui/moqui-framework.git moqui
    - name: list of files 
      run: ls -la
    - name: change directory
      run: cd moqui/
    - name: list of files
      run: ls -la
    - name: List files in the repository
      run: sudo  apt-get install openjdk-11-jdk
    - name: List files in the repository
      run: sudo java -version   
    - name: List files in the repository
      run: ./gradlew getRuntime
    - name: build artifacts
      run: cd docker/simple
    - name: image build
      run: ./docker-build.sh
      
      
