name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: List files in the repository
      run: sudo -i
    - name: List files in the repository
      run: sudo  apt-get install openjdk-8-jdk
    - name: List files in the repository
      run: sudo java -version   
   
      
