name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: list of files
      run: ls -la
    - name: clone repository
      run: git clone https://github.com/moqui/moqui-framework.git
    - name: list of files 
      run: ls -la
    - name: change directory
      run: cd moqui-framework
      
      
