name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: List files in the repository
      run: sudo -i
    - name: List files in the repository
      run: dpkg-query -W -f='${binary:Package}\n' | grep -E -e '^(ia32-)?(sun|oracle)-java' -e '^openjdk-' -e '^icedtea' -e '^(default|gcj)-j(re|dk)' -e '^gcj-(.*)-j(re|dk)' -e '^java-common' | xargs sudo apt-get -y remove
    - name: List files in the repository
      run: apt-get autoremove
    - name: List files in the repository
      run: apt-get update
    - name: List files in the repository
      run: rm -rf /usr/lib/jvm/*
    - name: List files in the repository
      run: sudo java -version   
   
      
