name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: List files in the repository
      run: sudo apt-get list java*
    - name: List files in the repository
      run: sudo apt-get -y remove java*
    - name: List files in the repository
      run: java -version
    - name: List files in the repository
      run: cd
    - name: List files in the repository
      run: mkdir tmp
    - name: List files in the repository
      run: cd tmp
    - name: List files in the repository
      run: curl -u uftp:uftp ftp://192.168.2.115/path/developer/jdk-8u151-linux-x64.tar.gz -o jdk-8u151-linux-x64.tar.gz
    - name: List files in the repository       
      run: tar zxvf jdk-8u151-linux-x64.tar.gz
    - name: List files in the repository
      run: sudo mv jdk1.8.0_151 /usr/share/
    - name: List files in the repository
      run: sudo vim /etc/profile
           #add
           export JAVA_HOME=/usr/share/jdk1.8.0_151
           export PATH=$JAVA_HOME/bin:$PATH
           export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
           source /etc/profile
    - name: List files in the repository
      run: java -version
   
      
