name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: list of files
      run: ls -la
    - name: clone repository
      run: git clone git@github.com:kasi9643/moqui-framework.git
    - name: list of files 
      run: ls -la
      
      
      
